apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: weaveset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: worker
          image: weaveset-worker:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: REDIS_PASSWORD
              value: "npaulweaveset"
          volumeMounts:
            - name: site
              mountPath: /app/site
      volumes:
        - name: site
          persistentVolumeClaim:
            claimName: site-pvc
